apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: testapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: demo
        image: philipdounut/backend-image:latest
        ports:
        - containerPort: 3000
